export const getAmenities = (t) => [
  { value: "العروض", label: t("translations.offers") },
  { value: "مواقف سيارة مجاني", label: t("translations.freeParking") },
  { value: "انترنت مجاني", label: t("translations.freeInternet") },
  { value: "منطقة جلوس خارجية", label: t("translations.outdoorSeating") },
  { value: "منطقة جلوس داخلية", label: t("translations.indoorSeating") },
  { value: "منطقة تناول الطعام", label: t("translations.dining") },
  { value: "شامل الإفطار", label: t("translations.includeBreak") },
  { value: "مطبخ", label: t("translations.kitchen") },
  { value: "غسالة ملابس", label: t("translations.waching") },
  { value: "تلفزيون", label: t("translations.tv") },
  { value: "ماكينة تحضير الشاي/القهوة", label: t("translations.teaMaker") },
  { value: "خدمة تنظيف الغرف", label: t("translations.roomService") },
  { value: "جاكوزي", label: t("translations.Jacuzzi") },
  { value: "كرسي مساج", label: t("translations.messageChair") },
  {
    value: "ملائم لذوي الاحتياجات الخاصة",
    label: t("translations.accessible"),
  },
];
